name: 'Create .env file'
description: 'GitHub Action to create a .env file using shell environment variables and .env.example as a template.'
author: 'Germain Olea'
branding:
  icon: 'briefcase'
  color: 'gray-dark'
inputs:
  file_name:
    description: 'The filename for the envfile'
    default: '.env'
runs:
  using: "composite"
  steps:
    - name: Create .env file
      run: |
        chmod +x ./create_env.sh
        ./create_env.sh ${{ inputs.file_name }}
      shell: bash
